version: "3.3"

services:
    nginx:
        image: nginx:1.21.3
        network_mode: host
        ports:
            - 80:80
            - 433:433
        depends_on:
            - anagrams
        volumes:
            - /anagrams/nginx.conf:/etc/nginx/conf.d/default.conf
            - /anagrams/cert/:/etc/nginx/cert/
        command: ["nginx", "-g", "daemon off;"]
        restart: unless-stopped

    anagrams:
        image: grubbcc/anagrams:latest
        network_mode: host
        volumes:
            - /anagrams/prefs/:/root/.java/.userPrefs/client/
            - /anagrams/gamelogs/:/anagrams/gamelogs/
            - /anagrams/log.log:/anagrams/log.log
        restart: unless-stopped