version: "3.3"

services:
    nginx:
        image: nginx:1.21.3
        ports:
            - 80:80
            - 433:433
        depends_on:
            - anagrams
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
#           - /anagrams/cert/:/etc/nginx/cert/
        command: ["nginx", "-g", "daemon off;"]
#        restart: unless-stopped

    anagrams:
        image: anagrams:latest
        ports:
            - 8079:8079
            - 8116:8116
        volumes:
            - ./prefs/:/root/.java/.userPrefs/client/
            - ./gamelogs/:/anagrams/gamelogs/
            - ./log.log:/anagrams/log.log
            - ./chat.log:/anagrams/chat.log
#        restart: unless-stopped